# Generated by Django 4.2.15 on 2024-09-01 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MaxValueValidator(75)]),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='gluten_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
